version: "3"

services:
  product:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/product
    depends_on:
      - "mongo"
    networks:
      - backend
  order:
    build: .
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - .:/order
    depends_on:
      - "mongo"
    networks:
      - backend

  mongo:
    container_name: "mongo-product"
    platform: linux/amd64
    image: mongo:4.4.14
    ports:
      - "8080:8080"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - backend

networks:
  backend:
    driver: bridge